version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    ignore:
      # Jakarta versions need to match the chosen Jakarta EE version
      - dependency-name: "jakarta.*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    groups:
      all-minor:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      all:
        patterns:
          - "*"
