services:
  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.2"
    user: "${UID:-1000}:${GID:-1000}"
    command: ["start-dev"]
    ports:
      - "8080:8080"
    environment:
      - "KEYCLOAK_ADMIN=kcadmin"
      - "KEYCLOAK_ADMIN_PASSWORD=kcadmin"
    volumes:
      - "./.docker/keycloak:/opt/keycloak/data"

  keycloak-config:
    image: "quay.io/adorsys/keycloak-config-cli:latest-24.0.1"
    environment:
      - "KEYCLOAK_URL=http://keycloak:8080"
      - "KEYCLOAK_USER=kcadmin"
      - "KEYCLOAK_PASSWORD=kcadmin"
      - "KEYCLOAK_AVAILABILITYCHECK_ENABLED=true"
      - "IMPORT_FILES_LOCATIONS=/config/*"
      - "IMPORT_VARSUBSTITUTION_ENABLED=true"
      - "APP_BASE_URL=http://localhost:8000"
      - "APP_CLIENT_SECRET=example"
    volumes:
      - "./keycloak/config/:/config/:ro"
