services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.0"
    user: "${UID:-1000}:${GID:-1000}"
    command: ["start-dev"]
    ports:
      - "8080:8080"
    environment:
      - "KC_BOOTSTRAP_ADMIN_USERNAME=kcadmin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=kcadmin"
    volumes:
      - "./.docker/keycloak:/opt/keycloak/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak-config:
    image: "quay.io/adorsys/keycloak-config-cli:latest-26"
    environment:
      - "KEYCLOAK_URL=http://keycloak:8080"
      - "KEYCLOAK_USER=kcadmin"
      - "KEYCLOAK_PASSWORD=kcadmin"
      - "KEYCLOAK_AVAILABILITYCHECK_ENABLED=true"
      - "IMPORT_FILES_LOCATIONS=/config/*"
      - "IMPORT_VARSUBSTITUTION_ENABLED=true"
      - "APP_BASE_URL=http://localhost:8000"
      - "APP_BACKCHANNEL_BASE_URL=http://host.docker.internal:8000"
      - "APP_CLIENT_SECRET=example"
    volumes:
      - "./keycloak/config/:/config/:ro"
