name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "21"

      - uses: "gradle/actions/setup-gradle@v4"

      - run: "./gradlew build"

      - run: |
          docker compose up --quiet-pull -d
          docker compose up keycloak-config
          ./gradlew functionalTest
          docker compose down

      - uses: "actions/upload-artifact@v4"
        if: "always()"
        with:
          name: "test-reports"
          path: |
            **/build/reports/
            **/build/test-results/
