name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"

      - uses: "actions/setup-java@v5"
        with:
          distribution: "temurin"
          java-version: "21"

      - uses: "gradle/actions/setup-gradle@v4"

      - run: "./gradlew build"

      - name: "Run ./gradlew functionalTest"
        run: |
          docker compose pull --quiet
          docker compose up -d
          docker compose up --exit-code-from=keycloak-config keycloak-config
          ./gradlew functionalTest
          docker compose down -v

      - uses: "actions/upload-artifact@v4"
        if: "always()"
        with:
          name: "test-reports"
          path: |
            **/build/reports/
            **/build/test-results/
